Repository theepiccode/Awesome-IoT-Resources, pull requests merged in 2021-09, with the labels that each got.

#8 Fixing (almost) all errors
  README.md
Labels: bug :bug:

#2 Add Link Checker CICD
  .github/workflows/main.yml
  Banner.png
  CODE_OF_CONDUCT.md
  README.md
Labels: DevOps :repeat:

#14 Create greetings.yml
  .github/workflows/greetings.yml
Labels: DevOps :repeat:

#17 Added banner and badges for social media
  README.md
Labels: feature :rocket:

#19 Added tables and removed ToC
  README.md
Labels: feature :rocket:
